# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_data_added',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='parent_guardian_contact_number',
        ),
        migrations.RemoveField(
            model_name='patient_anc',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='patient_anc',
            name='parent_guardian_contact_number',
        ),
        migrations.RemoveField(
            model_name='patient_inpatient',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='patient_inpatient',
            name='parent_guardian_contact_number',
        ),
        migrations.RemoveField(
            model_name='patient_iwc',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='patient_iwc',
            name='parent_guardian_contact_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='patientid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Visit'),
        ),
        migrations.AddField(
            model_name='visit',
            name='patient_who_visited',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Patient'),
        ),
    ]
