# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_patient_patientid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Patient_firstname',
            new_name='patient_firstname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Patient_lastname',
            new_name='patient_lastname',
        ),
        migrations.RenameField(
            model_name='patient_anc',
            old_name='Patient_firstname',
            new_name='patient_firstname',
        ),
        migrations.RenameField(
            model_name='patient_anc',
            old_name='Patient_lastname',
            new_name='patient_lastname',
        ),
        migrations.RenameField(
            model_name='patient_inpatient',
            old_name='Patient_firstname',
            new_name='patient_firstname',
        ),
        migrations.RenameField(
            model_name='patient_inpatient',
            old_name='Patient_lastname',
            new_name='patient_lastname',
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_who_visited',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
    ]
