# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190402_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='associated_appointment',
            new_name='associated_visit',
        ),
        migrations.RenameField(
            model_name='patient_diagnosis',
            old_name='associated_diagnosis',
            new_name='associated_visit',
        ),
        migrations.RenameField(
            model_name='patient_imaging',
            old_name='associated_imaging',
            new_name='associated_visit',
        ),
        migrations.RenameField(
            model_name='patient_labs',
            old_name='associated_labs',
            new_name='associated_visit',
        ),
        migrations.RenameField(
            model_name='patient_medications',
            old_name='associated_medications',
            new_name='associated_visit',
        ),
        migrations.RenameField(
            model_name='patient_vitals',
            old_name='associated_vitals',
            new_name='associated_visit',
        ),
        migrations.AddField(
            model_name='diagnosis_class',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnosis_class',
            name='diagnosis_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='imaging_class',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imaging_class',
            name='imaging_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='labs_class',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labs_class',
            name='labs_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='medications_class',
            name='medication_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='patient_medications',
            name='medications',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.medications_class'),
        ),
        migrations.AddField(
            model_name='patient_medications',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anc_labs',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.anc_visit'),
        ),
        migrations.AlterField(
            model_name='anc_visit',
            name='anc_patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_anc'),
        ),
        migrations.AlterField(
            model_name='anc_vitals',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.anc_visit'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.provider'),
        ),
        migrations.AlterField(
            model_name='diagnosis_class',
            name='diagnosis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_diagnosis'),
        ),
        migrations.AlterField(
            model_name='imaging_class',
            name='imaging',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_imaging'),
        ),
        migrations.AlterField(
            model_name='iwc_labs',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.iwc_visit'),
        ),
        migrations.AlterField(
            model_name='iwc_visit',
            name='iwc_patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_iwc'),
        ),
        migrations.AlterField(
            model_name='iwc_vitals',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.iwc_visit'),
        ),
        migrations.AlterField(
            model_name='labs_class',
            name='labs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_labs'),
        ),
        migrations.AlterField(
            model_name='medications_class',
            name='medications',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_medications'),
        ),
        migrations.AlterField(
            model_name='patient_diagnosis',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.visit'),
        ),
        migrations.AlterField(
            model_name='patient_diagnosis',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient_imaging',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.visit'),
        ),
        migrations.AlterField(
            model_name='patient_labs',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.visit'),
        ),
        migrations.AlterField(
            model_name='patient_labs',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient_medications',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.visit'),
        ),
        migrations.AlterField(
            model_name='patient_vitals',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.visit'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_who_visited',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.provider'),
        ),
    ]
