# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190402_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_medications',
            name='medications',
        ),
        migrations.AlterField(
            model_name='anc_labs',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.anc_visit'),
        ),
        migrations.AlterField(
            model_name='anc_visit',
            name='anc_patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_anc'),
        ),
        migrations.AlterField(
            model_name='anc_vitals',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.anc_visit'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.provider'),
        ),
        migrations.AlterField(
            model_name='diagnosis_class',
            name='diagnosis',
            field=models.CharField(max_length=10, unique=True, verbose_name='patient_diagnosis'),
        ),
        migrations.AlterField(
            model_name='imaging_class',
            name='imaging',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_imaging'),
        ),
        migrations.AlterField(
            model_name='iwc_labs',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.iwc_visit'),
        ),
        migrations.AlterField(
            model_name='iwc_visit',
            name='iwc_patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_iwc'),
        ),
        migrations.AlterField(
            model_name='iwc_vitals',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.iwc_visit'),
        ),
        migrations.AlterField(
            model_name='labs_class',
            name='labs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_labs'),
        ),
        migrations.AlterField(
            model_name='medications_class',
            name='medications',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_medications'),
        ),
        migrations.AlterField(
            model_name='patient_diagnosis',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.visit'),
        ),
        migrations.AlterField(
            model_name='patient_imaging',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.visit'),
        ),
        migrations.AlterField(
            model_name='patient_labs',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.visit'),
        ),
        migrations.AlterField(
            model_name='patient_medications',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.visit'),
        ),
        migrations.AlterField(
            model_name='patient_vitals',
            name='associated_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.visit'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_who_visited',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.provider'),
        ),
    ]
